# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, upload_to='products/Y%/m%/d%'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, upload_to='products/Y%/m%/d%'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, upload_to='products/Y%/m%/d%'),
        ),
    ]
